# Generated by Django 5.0.1 on 2024-01-22 21:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('idCategoria', models.IntegerField(primary_key=True, serialize=False, verbose_name='Id de Categoria')),
                ('nombreCategoria', models.CharField(blank=True, max_length=50, verbose_name='Nombre de Categoria')),
            ],
        ),
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('idProducto', models.IntegerField(primary_key=True, serialize=False, verbose_name='Id de Producto')),
                ('nombreProducto', models.CharField(blank=True, max_length=50, verbose_name='Nombre de Producto')),
                ('descripcionProducto', models.CharField(blank=True, max_length=100, verbose_name='Descripcion de Producto')),
                ('precioProducto', models.IntegerField(verbose_name='Precio de Producto')),
                ('stockProducto', models.IntegerField(verbose_name='Stock de Producto')),
                ('categoriaProducto', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='carrito.categoria', verbose_name='Categoria')),
            ],
        ),
    ]
