# Generated by Django 5.0.1 on 2024-01-23 20:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carrito', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to='imagenes', verbose_name='imagen'),
        ),
        migrations.AlterField(
            model_name='producto',
            name='descripcionProducto',
            field=models.CharField(blank=True, max_length=100, verbose_name='Descripcion Producto'),
        ),
        migrations.AlterField(
            model_name='producto',
            name='idProducto',
            field=models.IntegerField(primary_key=True, serialize=False, verbose_name='Id Producto'),
        ),
        migrations.AlterField(
            model_name='producto',
            name='nombreProducto',
            field=models.CharField(blank=True, max_length=50, verbose_name='Nombre Producto'),
        ),
        migrations.AlterField(
            model_name='producto',
            name='precioProducto',
            field=models.IntegerField(verbose_name='Precio Producto'),
        ),
        migrations.AlterField(
            model_name='producto',
            name='stockProducto',
            field=models.IntegerField(verbose_name='Stock Producto'),
        ),
    ]
